### ISSUE TITLE
Не удается скачать http://mintmanga.com/food_wars_

### ISSUE THREAD

**Issue by Vadimatorik** [4ndv/mrmanga#5]
Программу запускал на той же машине, где качал успешно раньше (Ubuntu 16.04). Скрипт на всякий случай обновил. 
```
vadim@vadim-Aspire-V3-371:~/project/mrmanga$ sudo gem install mrmanga
[sudo] password for vadim: 
Successfully installed mrmanga-0.9.0
Parsing documentation for mrmanga-0.9.0
Done installing documentation for mrmanga after 0 seconds
1 gem installed
vadim@vadim-Aspire-V3-371:~/project/mrmanga$ sudo mrmanga
Welcome to mrmanga 0.9.0!
It will create folders into CURRENT PATH!!
Tell me the link of the manga you want to download (example: http://readmanga.me/your_name)?  http://mintmanga.com/food_wars_
Just press Enter to download all the volumes, or specity volumes using this: 1-5 or this: 1, 2, 3, 4, 5 (or 1,2,3,4,5) syntaxes. Also you can download one volume by entering it's number (like this: 1)
Which volumes should i download?  |all|  
How many threads should i use to download? (6)  
Create pdfs for volumes?  |yes|

Add pages in PDF outline?  |yes|

Parsing manga info

/var/lib/gems/2.3.0/gems/nokogiri-1.8.4/lib/nokogiri/xml/node_set.rb:178:in `attr': undefined method `attribute' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/mrmanga-0.9.0/lib/mrmanga/parser.rb:18:in `get_manga'
	from /var/lib/gems/2.3.0/gems/mrmanga-0.9.0/lib/mrmanga/cli.rb:58:in `interactive_shell'
	from /var/lib/gems/2.3.0/gems/mrmanga-0.9.0/exe/mrmanga:5:in `<top (required)>'
	from /usr/local/bin/mrmanga:23:in `load'
```

**Comment by 4ndv** [comment]
Минтманга чутка изменили верстку, попробую сделать так, чтобы работала и ридманга и минтманга без разделения парсеров

**Comment by 4ndv** [comment]
Пофиксил, через несколько минут будет доступно в rubygems.

Обновление:
```sh
(sudo) gem install mrmanga
```

**Comment by 4ndv** [comment]
`0.10.0` уже в rubygems. В случае если проблема осталась - прошу заново открыть эту ишшую, спасибо за репорт!
